apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Data Science Pipelines
  - ./routes/ds-pipelines-route.yaml
  - ./routes/minio-route.yaml

  # Initalize Minio Bucket With Mnist Data
  - ./init-bucket/creation-script.yaml
  - ./init-bucket/creation-job.yaml

  # Add Notebook Imagestreams for RHODS
  - ./notebook-images/ds-notebook-cuda-is.yaml
  - ./notebook-images/ds-notebook-is.yaml

  # Setup Data Science Project
  - ./data-science-project/ns.yaml
  - ./data-science-project/pvc.yaml
  - ./data-science-project/s3-connection-secret.yaml
  # @TODO: Add notebook
  # - ./data-science-project/notebook-cuda.yaml

  # Visualization server fix viewer-crd role
  - ./visualization-server/role.yaml
  - ./visualization-server/rolebinding.yaml
  - ./visualization-server/viewer.yaml
  - ./visualization-server/route.yaml

patches:
- target:
    version: v1
    kind: Secret
    name: aws-connection-s3-creds
  patch: |-
    - op: replace
      path: /stringData/AWS_S3_ENDPOINT
      value: http://minio-redhat-ods-applications.apps.snogpu.redhat.hpecic.net
- target:
    version: v1beta1
    group: kubeflow.org
    kind: Viewer
    name: my-viewer
  patch: |-
    - op: replace
      path: /spec/podTemplateSpec/spec/containers/0/env/2/value
      value: http://minio-redhat-ods-applications.apps.snogpu.redhat.hpecic.net
